- hosts: all
  tasks:
    - name: Send release announcement
      command: >
        {{ zuul.build }}/src/opendev.org/openstack/releases/tools/announce.sh
          {{ zuul.build }}/src/{{ zuul.project.canonical_name }} {{ zuul.tag }}
